<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lewati</name>
   <tag></tag>
   <elementGuidId>c96074b7-85b8-4f87-a53f-c2fa0f98119b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//android.widget.Button[@content-desc=&quot;Lewati&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
